'use strict'

/** Enrich Alpha 失败/状态码（报告用 · 不阻断默认推送） */
const ENRICH_CODES = Object.freeze({
  FETCH_TIMEOUT: 'FETCH_TIMEOUT',
  WEB_FETCH_FAILED: 'WEB_FETCH_FAILED',
  WECHAT_PAYWALL: 'WECHAT_PAYWALL',
  PARSE_EMPTY: 'PARSE_EMPTY',
  WECHAT_T1_OK: 'WECHAT_T1_OK',
  WECHAT_T4_META: 'WECHAT_T4_META',
  WEB_DEFUDDLE_OK: 'WEB_DEFUDDLE_OK',
  WEB_META_OK: 'WEB_META_OK',
  CACHE_HIT: 'CACHE_HIT',
  SKIPPED: 'SKIPPED',
  DEGRADED: 'DEGRADED'
})

module.exports = { ENRICH_CODES }
